### ISSUE TITLE
unhashable type: 'set'

### ISSUE THREAD

**Issue by taojinglong** [Featuretools/predict-remaining-useful-life#7]
![image](https://user-images.githubusercontent.com/32380423/60067133-fde4b680-973b-11e9-9559-87040a96b99c.png)

**Comment by kmax12** [comment]
This was fixed in https://github.com/Featuretools/featuretools/pull/615, which will be released in the next version of Featuretools. In the meantime, can you try to install Featuretools directly from master?

That can be done with the following command

```pip install --upgrade https://github.com/featuretools/featuretools/zipball/master```

The other option is to update to pandas 0.24.2.

Please let us know if that helps.

**Comment by kmax12** [comment]
This fixed and has been released in Featuretools 0.9.1. If you upgrade to the latest version of Featuretools, it will go away.
